### ISSUE TITLE
eyedetection

### ISSUE THREAD

**Issue by xulong20130712** [hujiaweibujidao/XFace#1]
为什么我把OpencvManager中的so解压出来放到eye detection工程中，并且load，运行还是要让我按OpencvManager，求教，在线急等。谢谢

**Comment by hujiaweibujidao** [comment]
要想不安装OpencvManager，并不是简单把它的so放到你的项目中，相关内容请看 [我之前的这篇文章](http://hujiaweibujidao.github.io/blog/2013/11/18/android-ndk-and-opencv-development-3/)，希望有用。

**Comment by xulong20130712** [comment]
好，谢谢。
