### ISSUE TITLE
as版本下的注册人脸图像的时候，没看懂逻辑，关键的是自动获取？还是，界面也没有button什么的，怎么保存自己的人脸图片啊，求解答

### ISSUE THREAD

**Issue by msandroid** [hujiaweibujidao/XFace#2]

**Comment by hujiaweibujidao** [comment]
mface是自动获取，需要注意距离和周边环境，比较难抓取

xface是手动点击保存图片

**Comment by msandroid** [comment]
我不知道是我没理解清楚还是as版本本来就有问题，没地方可点击啊，没有相关button，点击照相区域也没反应

在 2016-03-31 22:03:02，"潇涧" <notifications@github.com> 写道：


mface是自动获取，需要注意距离和周边环境，比较难抓取

xface是手动点击保存图片
